### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by EternityForest** [anonymousAwesome/Randomly-generated-Magic-Items#3]
Looks like an awesome project, but I don't see a license? Can this be used in games?

**Comment by anonymousAwesome** [comment]
As far as I'm concerned, this is released under the WTFPL, or Do **W**hatever **T**he **F**uck You Want **P**ublic **L**icence.

If you do wind up using it for a public project I'd love to see what you've done with it, but that's not a requirement or anything.
